# Generated by Django 5.0.1 on 2024-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('punch', models.CharField(max_length=20)),
                ('time', models.TimeField(auto_now=True)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
            },
        ),
    ]
