# Generated by Django 5.0.1 on 2024-01-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='time',
            new_name='time_punched',
        ),
    ]
