# Generated by Django 5.0.1 on 2024-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytime', '0002_rename_date_timeentry_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='time_punched',
            field=models.TimeField(),
        ),
    ]
