# Generated by Django 5.0.1 on 2024-01-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytime', '0003_alter_timeentry_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='punch',
            field=models.CharField(choices=[('ClockedIn', 'CLOCKED_IN'), ('ClockedOut', 'CLOCKED_OUT')], max_length=10),
        ),
    ]
