# Generated by Django 5.0.1 on 2024-01-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytime', '0004_alter_timeentry_punch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
